GET http://localhost:5000/api/size 

###
POST http://localhost:5000/api/size
Content-Type: application/json

{
    "Name": "XXL"
}
###
PUT http://localhost:5000/api/size/614c8ad2d25a44a98d1a8f97
Content-Type: application/json

{
    "Name": "X.1"
}
###
DELETE http://localhost:5000/api/size/614c8ad2d25a44a98d1a8f97
