POST http://localhost:5000/user/register 
Content-Type: application/json

{
    "Fullname": "Toàn",
    "Email": "admin3@gmail.com",
    "Password": "12345678",
    "PasswordConfirm": "12345678",
    "Phone": "0326714731"
}
###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "Email": "admin@gmail.com",
    "Password": "12345678"
}

###
GET http://localhost:5000/user/logout
###
GET http://localhost:5000/user/refresh_token
refreshtoken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDZkMTkwMzMwYjFjYTI2NGQwODY0ZCIsImlhdCI6MTYzMjA1OTY3MywiZXhwIjoxNjMyNjY0NDczfQ.DmWkWFAyvi2gOjavzTsb-k-s3iXiMksExkwTRgN-1ys

###
GET  http://localhost:5000/user/profile 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzZkZmRmMjUxMzI5ZGExNjdlYTkyYiIsImlhdCI6MTYzMjE1MjQwOSwiZXhwIjoxNjMyMTUzMDY5fQ.VOgJv8HkX1whOHvWCcIOHWvjY8x_A1jnmaQGBi0XMPU

###
PUT http://localhost:5000/user/profile
Content-Type: application/json

{
    "Address": "Nguyễn Văn Cừ",
    "Birthday": "1999-12-12",
    "Email": "admin@gmail.com",
    "Fullname": "Trần Minh Toàn",
    "Phone": "0326714733",
    "Role": 1,
    "Sex": "Female",
    "_id": "6136dfdf251329da167ea92b"
}


###
GET  http://localhost:5000/user/loaduser 

###
GET  http://localhost:5000/user/oneuser/6136dfdf251329da167ea92b